# Generated by Django 4.1.5 on 2023-03-12 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lectuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('bdy', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('cors_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 16, 53, 26, 547044))),
            ],
        ),
    ]
