# Generated by Django 4.1.5 on 2023-03-14 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corse', '0002_corses_alter_lectuer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectuer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 17, 27, 48, 297218)),
        ),
    ]
