# Generated by Django 4.1.5 on 2023-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corse', '0007_alter_lectuer_date'),
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faver_corses',
            field=models.ManyToManyField(to='corse.corses'),
        ),
    ]
