# Generated by Django 4.1.5 on 2023-05-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_userprofile_faver_corses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='faver_corses',
        ),
    ]
