# Generated by Django 4.1.5 on 2023-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
