# Generated by Django 4.1.5 on 2023-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corse', '0015_alter_lectuer_date'),
        ('acount', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cors_fav',
            field=models.ManyToManyField(to='corse.corses'),
        ),
    ]
